# Generated by Django 6.1.1 on 2026-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='production_date',
            field=models.DateField(verbose_name='Production Date'),
        ),
    ]
